"""AI Avatar Generation routes - OpenAI GPT Image 1 & Gemini Nano Banana."""

import os
import base64
import uuid
import logging
from datetime import datetime, timezone
from fastapi import APIRouter, HTTPException, Request
from pydantic import BaseModel
from dotenv import load_dotenv

from routes.db import db, get_current_user

load_dotenv()

logger = logging.getLogger(__name__)
router = APIRouter()

EMERGENT_LLM_KEY = os.environ.get("EMERGENT_LLM_KEY", "")

AVATAR_SYSTEM_PREFIX = (
    "Generate a professional, high-quality profile avatar image. "
    "The image should be a close-up portrait with a clean background, "
    "suitable for use as a profile picture. Style: "
)


class GenerateAvatarRequest(BaseModel):
    prompt: str
    provider: str = "openai"  # "openai" or "gemini"
    save_as_profile: bool = False


@router.post("/auth/generate-avatar")
async def generate_avatar(req: GenerateAvatarRequest, request: Request):
    """Generate an AI avatar using OpenAI GPT Image 1 or Gemini Nano Banana."""
    user = await get_current_user(request)
    if not user:
        raise HTTPException(status_code=401, detail="Not authenticated")

    if not req.prompt or len(req.prompt.strip()) < 3:
        raise HTTPException(status_code=400, detail="Prompt must be at least 3 characters")

    if len(req.prompt) > 500:
        raise HTTPException(status_code=400, detail="Prompt must be under 500 characters")

    if not EMERGENT_LLM_KEY:
        raise HTTPException(status_code=500, detail="AI generation not configured")

    full_prompt = AVATAR_SYSTEM_PREFIX + req.prompt.strip()

    try:
        if req.provider == "gemini":
            image_b64 = await _generate_gemini(full_prompt)
        else:
            image_b64 = await _generate_openai(full_prompt)
    except Exception as e:
        logger.exception(f"AI avatar generation failed ({req.provider}): {e}")
        raise HTTPException(status_code=500, detail=f"Image generation failed: {str(e)}")

    data_uri = f"data:image/png;base64,{image_b64}"

    # Auto-save to avatar history
    history_id = f"avh_{uuid.uuid4().hex[:12]}"
    await db.avatar_history.insert_one({
        "history_id": history_id,
        "user_id": user.user_id,
        "data_uri": data_uri,
        "prompt": req.prompt.strip(),
        "provider": req.provider,
        "created_at": datetime.now(timezone.utc).isoformat(),
    })

    if req.save_as_profile:
        await db.users.update_one(
            {"user_id": user.user_id},
            {"$set": {
                "profile_image": data_uri,
                "updated_at": datetime.now(timezone.utc),
            }},
        )

    return {
        "image_base64": image_b64,
        "data_uri": data_uri,
        "provider": req.provider,
        "saved": req.save_as_profile,
        "history_id": history_id,
    }


@router.get("/auth/avatar-history")
async def get_avatar_history(request: Request):
    """Get the user's avatar generation history."""
    user = await get_current_user(request)
    if not user:
        raise HTTPException(status_code=401, detail="Not authenticated")

    cursor = db.avatar_history.find(
        {"user_id": user.user_id},
        {"_id": 0},
    ).sort("created_at", -1)

    items = await cursor.to_list(length=500)
    return {"items": items, "count": len(items)}


@router.delete("/auth/avatar-history/{history_id}")
async def delete_avatar_history_item(history_id: str, request: Request):
    """Delete a single avatar from history."""
    user = await get_current_user(request)
    if not user:
        raise HTTPException(status_code=401, detail="Not authenticated")

    result = await db.avatar_history.delete_one({
        "history_id": history_id,
        "user_id": user.user_id,
    })

    if result.deleted_count == 0:
        raise HTTPException(status_code=404, detail="History item not found")

    return {"status": "deleted", "history_id": history_id}


async def _generate_openai(prompt: str) -> str:
    """Generate image using OpenAI GPT Image 1."""
    from emergentintegrations.llm.openai.image_generation import OpenAIImageGeneration

    image_gen = OpenAIImageGeneration(api_key=EMERGENT_LLM_KEY)
    images = await image_gen.generate_images(
        prompt=prompt,
        model="gpt-image-1",
        number_of_images=1,
    )

    if not images or len(images) == 0:
        raise Exception("No image was generated by OpenAI")

    return base64.b64encode(images[0]).decode("utf-8")


async def _generate_gemini(prompt: str) -> str:
    """Generate image using Gemini Nano Banana."""
    from emergentintegrations.llm.chat import LlmChat, UserMessage

    session_id = f"avatar_{uuid.uuid4().hex[:8]}"
    chat = LlmChat(
        api_key=EMERGENT_LLM_KEY,
        session_id=session_id,
        system_message="You are a professional avatar image generator.",
    )
    chat.with_model("gemini", "gemini-3-pro-image-preview").with_params(modalities=["image", "text"])

    msg = UserMessage(text=prompt)
    text, images = await chat.send_message_multimodal_response(msg)

    if not images or len(images) == 0:
        raise Exception("No image was generated by Gemini")

    return images[0]["data"]
