"""Curated Learning Hub seed catalog: 25 diverse categories, 2 courses each."""

_RAW = [
    # slug, title, category, subcategory, difficulty, hours, overview, skills, modules[(title, outcome, mins)], featured
    ("ai-foundations", "Enterprise AI Foundations for Builders", "AI", "Machine Learning", "beginner", 6,
     "Master practical AI foundations, prompts, and production thinking.",
     ["AI Literacy", "Prompt Engineering", "Workflow Automation"],
     [("AI Fundamentals", "Understand model behavior", 40), ("Prompt Engineering", "Generate predictable outputs", 45), ("Deploying AI Workflows", "Ship AI features safely", 55)], True),
    ("ai-agents", "Building Autonomous AI Agents", "AI", "AI Agents", "advanced", 9,
     "Design, orchestrate, and ship multi-step AI agents for real business workflows.",
     ["Agent Orchestration", "Tool Calling", "Evaluation"],
     [("Agent Architectures", "Choose the right agent pattern", 50), ("Tools & Memory", "Wire tools and long-term memory", 55), ("Agent Evaluation", "Measure and harden agent quality", 60)], False),
    ("cyber-ai-teams", "Applied Cybersecurity for AI Teams", "Cybersecurity", "AI Security", "intermediate", 8,
     "Build secure AI systems with modern attack/defense playbooks.",
     ["Threat Modeling", "LLM Safety", "Incident Response"],
     [("Secure Prompt Design", "Reduce prompt injection risk", 50), ("Model Abuse Monitoring", "Detect abuse patterns", 45), ("Incident Response", "Respond to AI incidents", 60)], True),
    ("cyber-zero-trust", "Zero Trust Security Architecture", "Cybersecurity", "Network Security", "advanced", 10,
     "Implement zero trust principles across identity, network, and workloads.",
     ["Zero Trust", "IAM", "Network Segmentation"],
     [("Zero Trust Principles", "Map trust boundaries", 45), ("Identity & Access", "Deploy least-privilege access", 55), ("Continuous Verification", "Automate posture checks", 50)], False),
    ("it-support-pro", "IT Support Professional Bootcamp", "IT", "IT Support", "beginner", 7,
     "From ticket triage to endpoint management: become a dependable IT pro.",
     ["Troubleshooting", "Endpoint Management", "ITIL Basics"],
     [("Help Desk Mastery", "Resolve tickets fast and well", 40), ("OS & Hardware", "Diagnose common failures", 50), ("ITIL Foundations", "Run structured IT processes", 45)], False),
    ("it-sysadmin", "Modern Systems Administration", "IT", "System Administration", "intermediate", 9,
     "Automate server fleets, directory services, and patching at enterprise scale.",
     ["Linux Administration", "Automation", "Monitoring"],
     [("Linux at Scale", "Manage fleets with confidence", 55), ("Directory & Auth", "Operate SSO and directories", 45), ("Patch & Monitor", "Automate updates and alerts", 50)], False),
    ("software-fullstack", "Full-Stack Web Engineering", "Software", "Web Development", "intermediate", 12,
     "Ship production web apps end to end: API, UI, data, and deployment.",
     ["React", "APIs", "Databases"],
     [("Frontend Systems", "Build maintainable UIs", 60), ("API Design", "Design clean, versioned APIs", 55), ("Ship & Operate", "Deploy with CI/CD", 50)], True),
    ("software-architecture", "Software Architecture Patterns", "Software", "Architecture", "advanced", 10,
     "Master the architecture patterns behind resilient, scalable systems.",
     ["System Design", "Microservices", "Event-Driven Design"],
     [("Monolith to Services", "Split systems safely", 55), ("Event-Driven Systems", "Design async workflows", 55), ("Scaling Playbooks", "Handle 10x growth", 60)], False),
    ("ds-analytics", "Data Analytics with Python & SQL", "Data Science", "Analytics", "beginner", 8,
     "Turn raw data into decisions with SQL, pandas, and clear storytelling.",
     ["SQL", "Pandas", "Data Storytelling"],
     [("SQL Fluency", "Query anything, fast", 50), ("Python for Analysis", "Wrangle data with pandas", 55), ("Insight Narratives", "Present findings that land", 40)], False),
    ("ds-mlops", "Machine Learning in Production (MLOps)", "Data Science", "MLOps", "advanced", 11,
     "Take models from notebook to monitored production service.",
     ["MLOps", "Model Serving", "Drift Monitoring"],
     [("Pipelines & Registries", "Version data and models", 55), ("Serving Patterns", "Deploy low-latency inference", 55), ("Monitoring & Drift", "Keep models honest", 50)], False),
    ("cloud-aws-core", "Cloud Practitioner to Architect", "Cloud Computing", "Cloud Architecture", "intermediate", 10,
     "Design cost-efficient, highly available cloud architectures.",
     ["Cloud Design", "Cost Optimization", "High Availability"],
     [("Core Cloud Services", "Pick the right primitives", 50), ("HA & DR Design", "Survive zone failures", 55), ("FinOps Basics", "Cut cloud spend 30%", 45)], False),
    ("cloud-serverless", "Serverless Applications Masterclass", "Cloud Computing", "Serverless", "intermediate", 8,
     "Build event-driven serverless apps with functions, queues, and edge.",
     ["Serverless", "Event-Driven", "Edge Computing"],
     [("Functions First", "Model logic as functions", 45), ("Queues & Events", "Chain reliable workflows", 50), ("Edge Delivery", "Serve users from the edge", 45)], False),
    ("devops-cicd", "CI/CD Pipelines that Never Break", "DevOps", "CI/CD", "intermediate", 8,
     "Design fast, trustworthy delivery pipelines with progressive rollout.",
     ["CI/CD", "Testing Strategy", "Progressive Delivery"],
     [("Pipeline Design", "Build fast feedback loops", 50), ("Test Pyramids", "Balance speed and safety", 45), ("Canary & Rollback", "Release without fear", 50)], False),
    ("devops-kubernetes", "Kubernetes for Busy Engineers", "DevOps", "Containers", "advanced", 11,
     "Operate production Kubernetes: workloads, networking, and reliability.",
     ["Kubernetes", "Observability", "SRE Practices"],
     [("Workload Patterns", "Deploy and scale pods right", 55), ("Networking & Ingress", "Route traffic reliably", 55), ("SLOs & Incident Drills", "Run reliable clusters", 55)], False),
    ("biz-growth-ai", "AI for Growth, Marketing & Revenue", "Business", "Growth", "beginner", 5,
     "Use AI systems for campaign planning, conversion, and retention.",
     ["Growth Strategy", "Marketing AI", "Revenue Systems"],
     [("Offer Design", "Craft high-converting offers", 35), ("Audience Intelligence", "Analyze segments", 40), ("Campaign Loops", "Create growth loops", 40)], True),
    ("biz-strategy", "Business Strategy & Competitive Moats", "Business", "Strategy", "intermediate", 7,
     "Analyze markets, position products, and build durable advantages.",
     ["Strategy", "Market Analysis", "Positioning"],
     [("Market Mapping", "Size and segment markets", 45), ("Moat Building", "Design defensible advantages", 50), ("Strategic Bets", "Prioritize with conviction", 45)], False),
    ("mkt-performance", "Performance Marketing & Paid Growth", "Marketing", "Paid Acquisition", "intermediate", 7,
     "Run profitable paid campaigns across search, social, and retargeting.",
     ["Paid Ads", "Attribution", "CRO"],
     [("Channel Economics", "Model CAC and payback", 45), ("Creative Testing", "Iterate winning creatives", 45), ("Funnel CRO", "Lift conversion end to end", 50)], False),
    ("mkt-content-seo", "Content Marketing & SEO Engine", "Marketing", "SEO", "beginner", 6,
     "Build an organic growth engine with content clusters and technical SEO.",
     ["SEO", "Content Strategy", "Analytics"],
     [("Keyword Universes", "Find demand you can win", 40), ("Content Systems", "Publish at quality and scale", 45), ("Technical SEO", "Fix crawl and speed issues", 45)], False),
    ("ent-zero-to-one", "Startup Zero to One: Idea to Revenue", "Entrepreneurship", "Startup", "beginner", 8,
     "Validate ideas, land first customers, and reach repeatable revenue.",
     ["Validation", "Customer Discovery", "Early Sales"],
     [("Problem Discovery", "Interview like a founder", 45), ("MVP Sprints", "Ship the smallest sellable thing", 50), ("First 10 Customers", "Close early adopters", 50)], True),
    ("ent-fundraising", "Fundraising & Investor Storytelling", "Entrepreneurship", "Fundraising", "intermediate", 6,
     "Craft the narrative, metrics, and process to raise your round.",
     ["Pitching", "Financial Modeling", "Term Sheets"],
     [("Narrative Design", "Tell an irresistible story", 40), ("Metrics that Matter", "Show traction credibly", 45), ("Running the Round", "Create investor momentum", 45)], False),
    ("pm-agile-delivery", "Agile Project Delivery Mastery", "Project Management", "Agile", "intermediate", 7,
     "Plan, run, and rescue projects with agile and lean techniques.",
     ["Agile", "Scrum", "Risk Management"],
     [("Sprint Systems", "Run high-signal ceremonies", 45), ("Scope & Risk", "De-risk delivery early", 45), ("Stakeholder Ops", "Keep everyone aligned", 40)], False),
    ("pm-program-mgmt", "Enterprise Program Management", "Project Management", "Program Management", "advanced", 9,
     "Coordinate multi-team programs with dependencies, budgets, and OKRs.",
     ["Program Management", "OKRs", "Budgeting"],
     [("Program Blueprints", "Structure multi-team work", 50), ("Dependency Control", "Unblock across teams", 50), ("Executive Reporting", "Report with clarity", 45)], False),
    ("prod-discovery", "Product Discovery & User Research", "Product Management", "Discovery", "beginner", 6,
     "Find what users actually need before you build.",
     ["User Research", "Prototyping", "Prioritization"],
     [("Research Sprints", "Learn fast from users", 40), ("Opportunity Mapping", "Rank problems worth solving", 45), ("Prototype Tests", "Validate before building", 45)], False),
    ("prod-metrics", "Product Metrics & Experimentation", "Product Management", "Analytics", "intermediate", 7,
     "Define north-star metrics and run experiments that move them.",
     ["Product Analytics", "A/B Testing", "North Star Metrics"],
     [("Metric Trees", "Connect metrics to value", 45), ("Experiment Design", "Run trustworthy A/B tests", 50), ("Decision Frameworks", "Ship or kill with data", 40)], False),
    ("fin-personal", "Personal Finance & Wealth Building", "Finance", "Personal Finance", "beginner", 5,
     "Budgets, investing, and compounding: build wealth on any income.",
     ["Budgeting", "Investing", "Tax Basics"],
     [("Cashflow Control", "Master your money map", 35), ("Index Investing", "Build a simple portfolio", 40), ("Tax-Smart Moves", "Keep more of what you earn", 40)], False),
    ("fin-corporate", "Corporate Finance & Valuation", "Finance", "Valuation", "advanced", 9,
     "Read financial statements, model businesses, and value companies.",
     ["Financial Modeling", "Valuation", "Unit Economics"],
     [("Statement Fluency", "Read the three statements", 50), ("DCF & Multiples", "Value any business", 55), ("Unit Economics", "Model margin drivers", 45)], False),
    ("sales-b2b", "B2B Sales: Discovery to Close", "Sales", "B2B Sales", "intermediate", 7,
     "Run consultative sales cycles that close bigger deals faster.",
     ["Discovery Calls", "Negotiation", "Pipeline Management"],
     [("Discovery Excellence", "Uncover real pain", 45), ("Demos that Sell", "Show value, not features", 45), ("Negotiate & Close", "Protect price and terms", 50)], False),
    ("sales-social", "Social Selling & Outbound Systems", "Sales", "Outbound", "beginner", 6,
     "Build outbound machines: sequences, personalization, and replies.",
     ["Cold Outreach", "LinkedIn Selling", "Copywriting"],
     [("List Building", "Find perfect-fit prospects", 40), ("Message Craft", "Write replies-worthy outreach", 45), ("Sequence Systems", "Automate without spamming", 40)], False),
    ("lead-new-manager", "First-Time Manager Playbook", "Leadership", "Management", "beginner", 6,
     "Transition from IC to manager with 1:1s, feedback, and delegation.",
     ["1:1s", "Feedback", "Delegation"],
     [("Manager Mindset", "Lead through others", 40), ("Feedback Loops", "Give feedback that lands", 45), ("Delegation Systems", "Scale yourself safely", 40)], False),
    ("lead-executive", "Executive Leadership & Influence", "Leadership", "Executive Skills", "advanced", 8,
     "Operate at the executive level: vision, politics, and decision velocity.",
     ["Strategic Influence", "Decision Making", "Org Design"],
     [("Vision Setting", "Align orgs around direction", 50), ("Influence Maps", "Navigate stakeholders", 45), ("Decision Velocity", "Decide faster, better", 45)], False),
    ("hr-talent-acquisition", "Talent Acquisition & Hiring Excellence", "HR & Talent", "Recruiting", "intermediate", 6,
     "Design hiring funnels, structured interviews, and offer strategies.",
     ["Sourcing", "Structured Interviews", "Employer Brand"],
     [("Sourcing Engines", "Fill pipelines with A-players", 40), ("Interview Design", "Predict on-the-job success", 45), ("Closing Candidates", "Win competitive offers", 40)], False),
    ("hr-people-ops", "People Operations & Culture Design", "HR & Talent", "People Ops", "intermediate", 6,
     "Build performance, retention, and culture systems people love.",
     ["Performance Reviews", "Retention", "Culture Design"],
     [("Performance Systems", "Run fair, useful reviews", 45), ("Retention Playbooks", "Keep top performers", 40), ("Culture Rituals", "Design culture on purpose", 40)], False),
    ("design-uiux", "UI/UX Design from Zero to Portfolio", "Design", "UI/UX", "beginner", 9,
     "Learn research, wireframes, visual design, and ship a portfolio.",
     ["Figma", "Wireframing", "Design Systems"],
     [("UX Foundations", "Design around user goals", 50), ("Visual Craft", "Master hierarchy and type", 55), ("Portfolio Sprint", "Ship 3 case studies", 50)], True),
    ("design-systems", "Design Systems at Scale", "Design", "Design Systems", "advanced", 8,
     "Build token-based design systems that keep products consistent.",
     ["Design Tokens", "Component Libraries", "Accessibility"],
     [("Token Architecture", "Systematize color and space", 45), ("Component APIs", "Design flexible components", 50), ("Adoption & Governance", "Scale across teams", 45)], False),
    ("creative-illustration", "Digital Illustration Studio", "Creative Arts", "Illustration", "beginner", 7,
     "From sketch to finished digital art: composition, color, and style.",
     ["Digital Drawing", "Color Theory", "Composition"],
     [("Sketch Foundations", "Draw with confidence", 45), ("Color & Light", "Paint believable scenes", 50), ("Style Development", "Find your visual voice", 45)], False),
    ("creative-video", "Video Editing & Motion Graphics", "Creative Arts", "Video", "intermediate", 8,
     "Edit compelling videos and add motion graphics that pop.",
     ["Video Editing", "Motion Graphics", "Storyboarding"],
     [("Edit Rhythm", "Cut for emotion and pace", 50), ("Motion Basics", "Animate titles and scenes", 50), ("Delivery Pipelines", "Export for every platform", 40)], False),
    ("photo-fundamentals", "Photography Fundamentals", "Photography", "Fundamentals", "beginner", 6,
     "Master exposure, composition, and light with any camera.",
     ["Exposure", "Composition", "Lighting"],
     [("Exposure Triangle", "Control light deliberately", 40), ("Composition Rules", "Frame stronger photos", 40), ("Natural Light", "Shoot in any condition", 45)], False),
    ("photo-editing", "Photo Editing & Retouching Pro", "Photography", "Post-Production", "intermediate", 6,
     "Develop a signature look with professional editing workflows.",
     ["Lightroom", "Color Grading", "Retouching"],
     [("RAW Workflows", "Organize and develop RAW", 40), ("Color Grading", "Craft a signature look", 45), ("Portrait Retouch", "Retouch naturally", 45)], False),
    ("music-production", "Music Production Fundamentals", "Music", "Production", "beginner", 8,
     "Produce your first tracks: DAW skills, arrangement, and mixing.",
     ["DAW Skills", "Arrangement", "Mixing"],
     [("DAW Mastery", "Move fast in your DAW", 45), ("Arrangement", "Structure engaging tracks", 50), ("Mix Foundations", "Balance and polish mixes", 50)], False),
    ("music-theory", "Music Theory for Producers", "Music", "Theory", "intermediate", 6,
     "Chords, melodies, and harmony you can actually use in sessions.",
     ["Harmony", "Melody Writing", "Song Structure"],
     [("Chords that Work", "Build emotional progressions", 40), ("Melody Craft", "Write hooks that stick", 45), ("Structure & Tension", "Arrange with dynamics", 40)], False),
    ("writing-copywriting", "Copywriting that Converts", "Writing & Content", "Copywriting", "beginner", 6,
     "Write landing pages, emails, and ads that drive action.",
     ["Copywriting", "Persuasion", "Email Marketing"],
     [("Message Foundations", "Find the core promise", 40), ("Page & Ad Copy", "Write high-converting copy", 45), ("Email Sequences", "Nurture and convert", 40)], False),
    ("writing-storytelling", "Storytelling & Long-Form Writing", "Writing & Content", "Storytelling", "intermediate", 7,
     "Craft essays, scripts, and narratives people finish and share.",
     ["Narrative Structure", "Editing", "Voice"],
     [("Story Shapes", "Structure narratives that pull", 45), ("Voice & Style", "Develop a distinct voice", 45), ("Ruthless Editing", "Cut to the good part", 40)], False),
    ("lifestyle-productivity", "Deep Work & Personal Productivity", "Lifestyle", "Productivity", "beginner", 5,
     "Design focus systems, routines, and environments that compound.",
     ["Deep Work", "Habit Design", "Time Blocking"],
     [("Focus Systems", "Protect deep work daily", 35), ("Habit Engineering", "Make good habits automatic", 40), ("Weekly Reviews", "Course-correct every week", 35)], False),
    ("lifestyle-remote", "Remote Work & Digital Nomad Life", "Lifestyle", "Remote Work", "beginner", 5,
     "Thrive remotely: async communication, boundaries, and travel logistics.",
     ["Async Communication", "Remote Collaboration", "Work-Life Design"],
     [("Async Mastery", "Communicate without meetings", 35), ("Remote Rituals", "Stay visible and connected", 35), ("Nomad Logistics", "Work from anywhere safely", 40)], False),
    ("health-fitness", "Evidence-Based Fitness & Strength", "Health & Wellness", "Fitness", "beginner", 6,
     "Train smart with progressive overload, recovery, and nutrition basics.",
     ["Strength Training", "Nutrition", "Recovery"],
     [("Program Design", "Build a progressive plan", 40), ("Nutrition Basics", "Eat for your goals", 40), ("Recovery Science", "Sleep and deload right", 40)], False),
    ("health-mindfulness", "Mindfulness & Stress Resilience", "Health & Wellness", "Mental Wellness", "beginner", 4,
     "Practical meditation, breathwork, and stress tools for busy people.",
     ["Meditation", "Breathwork", "Stress Management"],
     [("Attention Training", "Meditate without mystery", 30), ("Breath Toolkit", "Downshift stress on demand", 30), ("Resilience Habits", "Build a calmer baseline", 35)], False),
    ("comm-public-speaking", "Public Speaking & Executive Presence", "Communication", "Public Speaking", "intermediate", 6,
     "Speak with clarity and presence in meetings, demos, and keynotes.",
     ["Public Speaking", "Storytelling", "Stage Presence"],
     [("Message Design", "Structure talks that land", 40), ("Delivery Skills", "Own voice and body language", 45), ("High-Stakes Rooms", "Handle Q&A under pressure", 40)], False),
    ("comm-negotiation", "Negotiation & Difficult Conversations", "Communication", "Negotiation", "intermediate", 6,
     "Negotiate salaries, deals, and conflicts with calm confidence.",
     ["Negotiation", "Conflict Resolution", "Active Listening"],
     [("Preparation Frames", "Know your leverage", 40), ("Live Tactics", "Steer tense conversations", 45), ("Durable Agreements", "Close win-win outcomes", 40)], False),
    ("pd-career-acceleration", "Career Acceleration Blueprint", "Personal Development", "Career Growth", "beginner", 6,
     "Position, negotiate, and grow your career faster with a clear system.",
     ["Career Strategy", "Personal Branding", "Negotiation"],
     [("Positioning", "Define your edge", 40), ("Visibility Systems", "Get known for great work", 40), ("Promotion Playbook", "Land the next level", 45)], True),
    ("pd-learning-how", "Learning How to Learn, Faster", "Personal Development", "Meta-Learning", "beginner", 5,
     "Use spaced repetition, deliberate practice, and recall to learn anything.",
     ["Spaced Repetition", "Deliberate Practice", "Note Systems"],
     [("Memory Mechanics", "Encode knowledge to last", 35), ("Practice Design", "Improve at the edge", 40), ("Knowledge Systems", "Build a second brain", 35)], False),
]


def build_seed_catalog(now_iso: str):
    docs = []
    for slug, title, category, sub, diff, hours, overview, skills, modules, featured in _RAW:
        docs.append({
            "seed_slug": slug,
            "title": title,
            "category": category,
            "subcategory": sub,
            "difficulty": diff,
            "duration_hours": hours,
            "adaptive_path": f"{category.lower().replace(' ', '-').replace('&', 'and')}-track",
            "overview": overview,
            "skills": list(skills),
            "modules": [
                {"module_id": f"m{i + 1}", "title": mt, "learning_outcome": mo, "estimated_minutes": mm}
                for i, (mt, mo, mm) in enumerate(modules)
            ],
            "featured": bool(featured),
            "auto_generated": False,
            "seeded": True,
            "created_at": now_iso,
            "updated_at": now_iso,
        })
    return docs
