apiVersion: apps/v1
kind: Deployment
metadata:
  name: communications-service
  labels:
    app: communications-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: communications-service
  template:
    metadata:
      labels:
        app: communications-service
    spec:
      containers:
        - name: communications-service
          image: realaicoach/communications-service:latest
          imagePullPolicy: IfNotPresent
          command: ["python", "-m", "uvicorn", "modules.communications_service_app:app", "--host", "0.0.0.0", "--port", "8102"]
          ports:
            - containerPort: 8102
          env:
            - name: MONGO_URL
              valueFrom:
                secretKeyRef:
                  name: realaicoach-backend
                  key: MONGO_URL
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: realaicoach-backend
                  key: DB_NAME

---
apiVersion: v1
kind: Service
metadata:
  name: communications-service
  labels:
    app: communications-service
spec:
  selector:
    app: communications-service
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8102
