export interface RouteE2EEvidenceTag {
  routePrefix: string;
  routeName: string;
  evidenceTag: string;
  verifiedAt: string;
  reportRefs: string[];
  liveDataApis: string[];
  promotedPhase: 'B';
  matchMode?: 'prefix' | 'exact';
}

// Wave 3: only promote routes that have explicit route-level evidence tags.
export const WAVE3_ROUTE_E2E_EVIDENCE_TAGS: RouteE2EEvidenceTag[] = [
  {
    routePrefix: '/',
    routeName: 'Root Home Route',
    evidenceTag: 'W3-E2E-ROOT-HOME-LIVE-20260508',
    verifiedAt: '2026-05-08T01:03:00Z',
    reportRefs: ['/app/test_reports/iteration_759.json'],
    liveDataApis: ['/home/stats', '/home/tour-status', '/onboarding-wizard/status'],
    promotedPhase: 'B',
    matchMode: 'exact',
  },
  {
    routePrefix: '/index',
    routeName: 'Root Index Route',
    evidenceTag: 'W3-E2E-ROOT-INDEX-LIVE-20260508',
    verifiedAt: '2026-05-08T01:08:00Z',
    reportRefs: ['/app/test_reports/iteration_759.json'],
    liveDataApis: ['/home/stats', '/home/tour-status', '/onboarding-wizard/status'],
    promotedPhase: 'B',
    matchMode: 'exact',
  },
  {
    routePrefix: '/(tabs)/index',
    routeName: 'Tabs Index Route',
    evidenceTag: 'W3-E2E-TABS-INDEX-LIVE-20260508',
    verifiedAt: '2026-05-08T01:08:00Z',
    reportRefs: ['/app/test_reports/iteration_759.json'],
    liveDataApis: ['/home/stats', '/home/tour-status', '/onboarding-wizard/status'],
    promotedPhase: 'B',
    matchMode: 'exact',
  },
  {
    routePrefix: '/home',
    routeName: 'Home Route Alias',
    evidenceTag: 'W3-E2E-HOME-ALIAS-LIVE-20260508',
    verifiedAt: '2026-05-08T01:08:00Z',
    reportRefs: ['/app/test_reports/iteration_759.json'],
    liveDataApis: ['/home/stats', '/home/tour-status', '/onboarding-wizard/status'],
    promotedPhase: 'B',
  },
  {
    routePrefix: '/dashboard',
    routeName: 'Home Dashboard Redirect Route',
    evidenceTag: 'W3-E2E-DASHBOARD-LIVE-20260508',
    verifiedAt: '2026-05-08T01:03:00Z',
    reportRefs: ['/app/test_reports/iteration_759.json'],
    liveDataApis: ['/home/stats', '/home/tour-status', '/onboarding-wizard/status'],
    promotedPhase: 'B',
  },
  {
    routePrefix: '/(tabs)',
    routeName: 'Home Tabs Cluster',
    evidenceTag: 'W3-E2E-TABS-HOME-LIVE-20260508',
    verifiedAt: '2026-05-08T01:03:00Z',
    reportRefs: ['/app/test_reports/iteration_759.json'],
    liveDataApis: ['/home/stats', '/home/tour-status', '/onboarding-wizard/status'],
    promotedPhase: 'B',
  },
  {
    routePrefix: '/content-library',
    routeName: 'Content Library Route',
    evidenceTag: 'W3-E2E-CONTENT-LIBRARY-LIVE-20260508',
    verifiedAt: '2026-05-08T01:03:00Z',
    reportRefs: ['/app/test_reports/iteration_759.json'],
    liveDataApis: ['/content/library', '/content/bookmarks/{user_id}', '/content/bookmarks/toggle'],
    promotedPhase: 'B',
  },
  {
    routePrefix: '/(tabs)/content-library',
    routeName: 'Tabs Content Library Route',
    evidenceTag: 'W3-E2E-TABS-CONTENT-LIBRARY-LIVE-20260508',
    verifiedAt: '2026-05-08T01:03:00Z',
    reportRefs: ['/app/test_reports/iteration_759.json'],
    liveDataApis: ['/content/library', '/content/bookmarks/{user_id}', '/content/bookmarks/toggle'],
    promotedPhase: 'B',
  },
  {
    routePrefix: '/profile',
    routeName: 'Profile Route',
    evidenceTag: 'W3-E2E-PROFILE-LIVE-20260508',
    verifiedAt: '2026-05-08T01:03:00Z',
    reportRefs: ['/app/test_reports/iteration_759.json'],
    liveDataApis: ['/progress/{user_id}', '/conversations/{user_id}'],
    promotedPhase: 'B',
  },
  {
    routePrefix: '/(tabs)/profile',
    routeName: 'Tabs Profile Route',
    evidenceTag: 'W3-E2E-TABS-PROFILE-LIVE-20260508',
    verifiedAt: '2026-05-08T01:03:00Z',
    reportRefs: ['/app/test_reports/iteration_759.json'],
    liveDataApis: ['/progress/{user_id}', '/conversations/{user_id}'],
    promotedPhase: 'B',
  },
  {
    routePrefix: '/my-analytics',
    routeName: 'My Analytics Route',
    evidenceTag: 'W4-E2E-MY-ANALYTICS-LIVE-20260508',
    verifiedAt: '2026-05-08T02:05:00Z',
    reportRefs: ['/app/test_reports/iteration_760.json'],
    liveDataApis: [
      '/user-analytics/dashboard',
      '/user-analytics/ai-usage-patterns',
      '/user-analytics/progress-trends',
      '/user-analytics/skill-radar',
      '/payments/analytics/my-dashboard',
    ],
    promotedPhase: 'B',
    matchMode: 'exact',
  },
  {
    routePrefix: '/integrations',
    routeName: 'Integrations Route',
    evidenceTag: 'W4-E2E-INTEGRATIONS-LIVE-20260508',
    verifiedAt: '2026-05-08T02:05:00Z',
    reportRefs: ['/app/test_reports/iteration_760.json'],
    liveDataApis: ['/integrations/available', '/integrations/', '/integrations/dashboard/stats'],
    promotedPhase: 'B',
    matchMode: 'exact',
  },
  {
    routePrefix: '/settings',
    routeName: 'Settings Enterprise Route',
    evidenceTag: 'W4-E2E-SETTINGS-LIVE-20260508',
    verifiedAt: '2026-05-08T02:05:00Z',
    reportRefs: ['/app/test_reports/iteration_760.json'],
    liveDataApis: ['/notifications/preferences', '/ai-briefing/preferences', '/auth/mfa/status'],
    promotedPhase: 'B',
    matchMode: 'exact',
  },
  {
    routePrefix: '/settings/index',
    routeName: 'Settings Index Route',
    evidenceTag: 'W4-E2E-SETTINGS-INDEX-LIVE-20260508',
    verifiedAt: '2026-05-08T02:05:00Z',
    reportRefs: ['/app/test_reports/iteration_760.json'],
    liveDataApis: ['/notifications/preferences', '/ai-briefing/preferences', '/auth/mfa/status'],
    promotedPhase: 'B',
    matchMode: 'exact',
  },
  {
    routePrefix: '/notifications',
    routeName: 'Notifications Workspace Route',
    evidenceTag: 'W5-E2E-NOTIFICATIONS-LIVE-20260508',
    verifiedAt: '2026-05-08T02:20:00Z',
    reportRefs: ['/app/test_reports/iteration_761.json'],
    liveDataApis: [
      '/notification-engine/summary',
      '/notifications/{user_id}',
      '/notifications/settings',
      '/notifications/bulk/read',
      '/notifications/bulk/archive',
    ],
    promotedPhase: 'B',
    matchMode: 'exact',
  },
  {
    routePrefix: '/help',
    routeName: 'Help Support Route',
    evidenceTag: 'W5-E2E-HELP-LIVE-20260508',
    verifiedAt: '2026-05-08T02:20:00Z',
    reportRefs: ['/app/test_reports/iteration_761.json'],
    liveDataApis: [
      '/support/faq',
      '/support/chat',
      '/support/chat/attachment',
      '/support/chat/audio',
      '/support/email/submit',
    ],
    promotedPhase: 'B',
    matchMode: 'exact',
  },
  {
    routePrefix: '/payment-history',
    routeName: 'Payment History Route',
    evidenceTag: 'W5-E2E-PAYMENT-HISTORY-LIVE-20260508',
    verifiedAt: '2026-05-08T02:20:00Z',
    reportRefs: ['/app/test_reports/iteration_761.json'],
    liveDataApis: [
      '/payments/history',
      '/payments/report-preferences',
      '/payments/receipt-transparency-mode',
      '/payments/send-report',
      '/payments/tax-statement/{format}',
    ],
    promotedPhase: 'B',
    matchMode: 'exact',
  },
  {
    routePrefix: '/book-meeting',
    routeName: 'Book Meeting (Agenda) Route',
    evidenceTag: 'W6-E2E-BOOK-MEETING-LIVE-20260508',
    verifiedAt: '2026-05-08T02:31:00Z',
    reportRefs: ['/app/test_reports/iteration_762.json'],
    liveDataApis: [
      '/calendar/events/{user_id}',
      '/calendar/status',
      '/calendar/events',
      '/calendar/ai-suggest',
      '/calendar/events/{event_id}/reschedule',
    ],
    promotedPhase: 'B',
    matchMode: 'exact',
  },
  {
    routePrefix: '/calendar',
    routeName: 'Calendar Route',
    evidenceTag: 'W6-E2E-CALENDAR-LIVE-20260508',
    verifiedAt: '2026-05-08T02:31:00Z',
    reportRefs: ['/app/test_reports/iteration_762.json'],
    liveDataApis: [
      '/calendar/status',
      '/calendar/calendars',
      '/calendar/events/{user_id}',
      '/calendar/reminders/{user_id}',
      '/calendar/smart-suggestions/{user_id}',
    ],
    promotedPhase: 'B',
    matchMode: 'exact',
  },
  {
    routePrefix: '/referrals',
    routeName: 'Referrals Route',
    evidenceTag: 'W6-E2E-REFERRALS-LIVE-20260508',
    verifiedAt: '2026-05-08T02:31:00Z',
    reportRefs: ['/app/test_reports/iteration_762.json'],
    liveDataApis: [
      '/referrals/my-stats',
      '/referrals/my-referrals',
      '/referrals/my-credits',
      '/referrals/my-milestones',
      '/referrals/sharing-kit',
    ],
    promotedPhase: 'B',
    matchMode: 'exact',
  },
  {
    routePrefix: '/content-library/',
    routeName: 'Content Library Trailing Slash Alias',
    evidenceTag: 'W7-E2E-CONTENT-LIBRARY-ALIAS-SLASH-20260508',
    verifiedAt: '2026-05-08T02:39:00Z',
    reportRefs: ['/app/test_reports/iteration_763.json'],
    liveDataApis: ['/content/library', '/content/bookmarks/{user_id}', '/content/bookmarks/toggle'],
    promotedPhase: 'B',
    matchMode: 'exact',
  },
  {
    routePrefix: '/(tabs)/content-library/index',
    routeName: 'Tabs Content Library Index Alias',
    evidenceTag: 'W7-E2E-TABS-CONTENT-LIBRARY-INDEX-20260508',
    verifiedAt: '2026-05-08T02:39:00Z',
    reportRefs: ['/app/test_reports/iteration_763.json'],
    liveDataApis: ['/content/library', '/content/bookmarks/{user_id}', '/content/bookmarks/toggle'],
    promotedPhase: 'B',
    matchMode: 'exact',
  },
  {
    routePrefix: '/certificate-gallery',
    routeName: 'Certificate Gallery Route',
    evidenceTag: 'W7-E2E-CERTIFICATE-GALLERY-LIVE-20260508',
    verifiedAt: '2026-05-08T02:39:00Z',
    reportRefs: ['/app/test_reports/iteration_763.json'],
    liveDataApis: ['/ai-learn/certificates', '/ai-learn/admin/certificates', '/ai-learn/admin/certificates/{verification_id}/revoke'],
    promotedPhase: 'B',
    matchMode: 'exact',
  },
  {
    routePrefix: '/leaderboard',
    routeName: 'Leaderboard Route',
    evidenceTag: 'W7-E2E-LEADERBOARD-LIVE-20260508',
    verifiedAt: '2026-05-08T02:39:00Z',
    reportRefs: ['/app/test_reports/iteration_763.json'],
    liveDataApis: ['/gamification/leaderboard', '/gamification/activity-feed', '/referrals/leaderboard-highlights', '/referrals/recent-activity'],
    promotedPhase: 'B',
    matchMode: 'exact',
  },
  {
    routePrefix: '/content-library/index',
    routeName: 'Content Library Index Alias',
    evidenceTag: 'W8-E2E-CONTENT-LIBRARY-INDEX-20260508',
    verifiedAt: '2026-05-08T02:50:00Z',
    reportRefs: ['/app/test_reports/iteration_764.json'],
    liveDataApis: ['/content/library', '/content/bookmarks/{user_id}', '/content/bookmarks/toggle'],
    promotedPhase: 'B',
    matchMode: 'exact',
  },
  {
    routePrefix: '/(tabs)/content-library/',
    routeName: 'Tabs Content Library Trailing Slash Alias',
    evidenceTag: 'W8-E2E-TABS-CONTENT-LIBRARY-SLASH-20260508',
    verifiedAt: '2026-05-08T02:50:00Z',
    reportRefs: ['/app/test_reports/iteration_764.json'],
    liveDataApis: ['/content/library', '/content/bookmarks/{user_id}', '/content/bookmarks/toggle'],
    promotedPhase: 'B',
    matchMode: 'exact',
  },
  {
    routePrefix: '/certificate-operations',
    routeName: 'Certificate Operations Route',
    evidenceTag: 'W8-E2E-CERTIFICATE-OPERATIONS-LIVE-20260508',
    verifiedAt: '2026-05-08T02:50:00Z',
    reportRefs: ['/app/test_reports/iteration_764.json'],
    liveDataApis: ['/ai-learn/admin/certificate-analytics', '/ai-learn/admin/certificates'],
    promotedPhase: 'B',
    matchMode: 'exact',
  },
  {
    routePrefix: '/my-tickets',
    routeName: 'My Tickets Route',
    evidenceTag: 'W8-E2E-MY-TICKETS-LIVE-20260508',
    verifiedAt: '2026-05-08T02:50:00Z',
    reportRefs: ['/app/test_reports/iteration_764.json'],
    liveDataApis: ['/tickets/my-tickets', '/tickets/my-tickets/analytics', '/tickets/submit', '/tickets/{ticket_id}/reply'],
    promotedPhase: 'B',
  },
  {
    routePrefix: '/progress',
    routeName: 'Progress Route',
    evidenceTag: 'W9-E2E-PROGRESS-LIVE-20260508',
    verifiedAt: '2026-05-08T03:10:00Z',
    reportRefs: ['/app/test_reports/iteration_766.json'],
    liveDataApis: ['/progress/{user_id}', '/progress-trends/{user_id}', '/session-history/{user_id}'],
    promotedPhase: 'B',
    matchMode: 'exact',
  },
  {
    routePrefix: '/my-analytics/',
    routeName: 'My Analytics Trailing Slash Alias',
    evidenceTag: 'W9-E2E-MY-ANALYTICS-SLASH-20260508',
    verifiedAt: '2026-05-08T03:10:00Z',
    reportRefs: ['/app/test_reports/iteration_766.json'],
    liveDataApis: ['/user-analytics/dashboard', '/payments/analytics/my-dashboard'],
    promotedPhase: 'B',
    matchMode: 'exact',
  },
  {
    routePrefix: '/my-analytics/index',
    routeName: 'My Analytics Index Alias',
    evidenceTag: 'W9-E2E-MY-ANALYTICS-INDEX-20260508',
    verifiedAt: '2026-05-08T03:10:00Z',
    reportRefs: ['/app/test_reports/iteration_766.json'],
    liveDataApis: ['/user-analytics/dashboard', '/payments/analytics/my-dashboard'],
    promotedPhase: 'B',
    matchMode: 'exact',
  },
  {
    routePrefix: '/integrations/',
    routeName: 'Integrations Trailing Slash Alias',
    evidenceTag: 'W9-E2E-INTEGRATIONS-SLASH-20260508',
    verifiedAt: '2026-05-08T03:10:00Z',
    reportRefs: ['/app/test_reports/iteration_766.json'],
    liveDataApis: ['/integrations/available', '/integrations/', '/integrations/dashboard/stats'],
    promotedPhase: 'B',
    matchMode: 'exact',
  },
  {
    routePrefix: '/integrations/index',
    routeName: 'Integrations Index Alias',
    evidenceTag: 'W9-E2E-INTEGRATIONS-INDEX-20260508',
    verifiedAt: '2026-05-08T03:10:00Z',
    reportRefs: ['/app/test_reports/iteration_766.json'],
    liveDataApis: ['/integrations/available', '/integrations/', '/integrations/dashboard/stats'],
    promotedPhase: 'B',
    matchMode: 'exact',
  },
  {
    routePrefix: '/book-meeting/',
    routeName: 'Book Meeting Trailing Slash Alias',
    evidenceTag: 'W10-E2E-BOOK-MEETING-SLASH-20260508',
    verifiedAt: '2026-05-08T10:05:00Z',
    reportRefs: ['/app/test_reports/iteration_767.json'],
    liveDataApis: ['/calendar/events/{user_id}', '/calendar/status', '/calendar/events', '/calendar/ai-suggest'],
    promotedPhase: 'B',
  },
  {
    routePrefix: '/book-meeting/index',
    routeName: 'Book Meeting Index Alias',
    evidenceTag: 'W10-E2E-BOOK-MEETING-INDEX-20260508',
    verifiedAt: '2026-05-08T10:05:00Z',
    reportRefs: ['/app/test_reports/iteration_767.json'],
    liveDataApis: ['/calendar/events/{user_id}', '/calendar/status', '/calendar/events', '/calendar/ai-suggest'],
    promotedPhase: 'B',
  },
  {
    routePrefix: '/calendar/',
    routeName: 'Calendar Trailing Slash Alias',
    evidenceTag: 'W10-E2E-CALENDAR-SLASH-20260508',
    verifiedAt: '2026-05-08T10:05:00Z',
    reportRefs: ['/app/test_reports/iteration_767.json'],
    liveDataApis: ['/calendar/status', '/calendar/calendars', '/calendar/events/{user_id}'],
    promotedPhase: 'B',
  },
  {
    routePrefix: '/calendar/index',
    routeName: 'Calendar Index Alias',
    evidenceTag: 'W10-E2E-CALENDAR-INDEX-20260508',
    verifiedAt: '2026-05-08T10:05:00Z',
    reportRefs: ['/app/test_reports/iteration_767.json'],
    liveDataApis: ['/calendar/status', '/calendar/calendars', '/calendar/events/{user_id}'],
    promotedPhase: 'B',
  },
  {
    routePrefix: '/notifications/',
    routeName: 'Notifications Trailing Slash Alias',
    evidenceTag: 'W10-E2E-NOTIFICATIONS-SLASH-20260508',
    verifiedAt: '2026-05-08T10:05:00Z',
    reportRefs: ['/app/test_reports/iteration_767.json'],
    liveDataApis: ['/notification-engine/summary', '/notifications/{user_id}', '/notifications/settings'],
    promotedPhase: 'B',
  },
  {
    routePrefix: '/notifications/index',
    routeName: 'Notifications Index Alias',
    evidenceTag: 'W10-E2E-NOTIFICATIONS-INDEX-20260508',
    verifiedAt: '2026-05-08T10:05:00Z',
    reportRefs: ['/app/test_reports/iteration_767.json'],
    liveDataApis: ['/notification-engine/summary', '/notifications/{user_id}', '/notifications/settings'],
    promotedPhase: 'B',
  },
  {
    routePrefix: '/settings/',
    routeName: 'Settings Trailing Slash Alias',
    evidenceTag: 'W11-E2E-SETTINGS-SLASH-20260508',
    verifiedAt: '2026-05-08T10:25:00Z',
    reportRefs: ['/app/test_reports/iteration_768.json'],
    liveDataApis: ['/notifications/preferences', '/ai-briefing/preferences', '/auth/mfa/status'],
    promotedPhase: 'B',
    matchMode: 'exact',
  },
  {
    routePrefix: '/payment-history/',
    routeName: 'Payment History Trailing Slash Alias',
    evidenceTag: 'W11-E2E-PAYMENT-HISTORY-SLASH-20260508',
    verifiedAt: '2026-05-08T10:25:00Z',
    reportRefs: ['/app/test_reports/iteration_768.json'],
    liveDataApis: ['/payments/history', '/payments/report-preferences', '/payments/send-report'],
    promotedPhase: 'B',
    matchMode: 'exact',
  },
  {
    routePrefix: '/payment-history/index',
    routeName: 'Payment History Index Alias',
    evidenceTag: 'W11-E2E-PAYMENT-HISTORY-INDEX-20260508',
    verifiedAt: '2026-05-08T10:25:00Z',
    reportRefs: ['/app/test_reports/iteration_768.json'],
    liveDataApis: ['/payments/history', '/payments/report-preferences', '/payments/send-report'],
    promotedPhase: 'B',
    matchMode: 'exact',
  },
  {
    routePrefix: '/help/',
    routeName: 'Help Trailing Slash Alias',
    evidenceTag: 'W11-E2E-HELP-SLASH-20260508',
    verifiedAt: '2026-05-08T10:25:00Z',
    reportRefs: ['/app/test_reports/iteration_768.json'],
    liveDataApis: ['/support/faq', '/support/chat', '/support/email/submit'],
    promotedPhase: 'B',
    matchMode: 'exact',
  },
  {
    routePrefix: '/help/index',
    routeName: 'Help Index Alias',
    evidenceTag: 'W11-E2E-HELP-INDEX-20260508',
    verifiedAt: '2026-05-08T10:25:00Z',
    reportRefs: ['/app/test_reports/iteration_768.json'],
    liveDataApis: ['/support/faq', '/support/chat', '/support/email/submit'],
    promotedPhase: 'B',
    matchMode: 'exact',
  },
  {
    routePrefix: '/ai-learning-hub',
    routeName: 'AI Learning Hub Route',
    evidenceTag: 'W12-E2E-AI-LEARNING-HUB-LIVE-20260508',
    verifiedAt: '2026-05-08T10:47:00Z',
    reportRefs: ['/app/test_reports/iteration_770.json'],
    liveDataApis: ['/ai-learn/catalog', '/ai-learn/generate-lesson', '/ai-learn/my-lessons'],
    promotedPhase: 'B',
    matchMode: 'exact',
  },
  {
    routePrefix: '/ai-learning-hub/',
    routeName: 'AI Learning Hub Trailing Slash Alias',
    evidenceTag: 'W12-E2E-AI-LEARNING-HUB-SLASH-20260508',
    verifiedAt: '2026-05-08T10:47:00Z',
    reportRefs: ['/app/test_reports/iteration_770.json'],
    liveDataApis: ['/ai-learn/catalog', '/ai-learn/generate-lesson', '/ai-learn/my-lessons'],
    promotedPhase: 'B',
    matchMode: 'exact',
  },
  {
    routePrefix: '/ai-learning-hub/index',
    routeName: 'AI Learning Hub Index Alias',
    evidenceTag: 'W12-E2E-AI-LEARNING-HUB-INDEX-20260508',
    verifiedAt: '2026-05-08T10:47:00Z',
    reportRefs: ['/app/test_reports/iteration_770.json'],
    liveDataApis: ['/ai-learn/catalog', '/ai-learn/generate-lesson', '/ai-learn/my-lessons'],
    promotedPhase: 'B',
    matchMode: 'exact',
  },
  {
    routePrefix: '/ai-coaching-team',
    routeName: 'AI Problem Solver Route',
    evidenceTag: 'W12-E2E-AI-PROBLEM-SOLVER-LIVE-20260508',
    verifiedAt: '2026-05-08T10:47:00Z',
    reportRefs: ['/app/test_reports/iteration_770.json'],
    liveDataApis: ['/ai-solver/categories', '/ai-solver/analyze', '/ai-solver/sessions'],
    promotedPhase: 'B',
    matchMode: 'exact',
  },
  {
    routePrefix: '/ai-coaching-team/',
    routeName: 'AI Problem Solver Trailing Slash Alias',
    evidenceTag: 'W12-E2E-AI-PROBLEM-SOLVER-SLASH-20260508',
    verifiedAt: '2026-05-08T10:47:00Z',
    reportRefs: ['/app/test_reports/iteration_770.json'],
    liveDataApis: ['/ai-solver/categories', '/ai-solver/analyze', '/ai-solver/sessions'],
    promotedPhase: 'B',
    matchMode: 'exact',
  },
  {
    routePrefix: '/ai-coaching-team/index',
    routeName: 'AI Problem Solver Index Alias',
    evidenceTag: 'W12-E2E-AI-PROBLEM-SOLVER-INDEX-20260508',
    verifiedAt: '2026-05-08T10:47:00Z',
    reportRefs: ['/app/test_reports/iteration_770.json'],
    liveDataApis: ['/ai-solver/categories', '/ai-solver/analyze', '/ai-solver/sessions'],
    promotedPhase: 'B',
    matchMode: 'exact',
  },
  {
    routePrefix: '/ai-briefing',
    routeName: 'AI Briefing Route',
    evidenceTag: 'W12-E2E-AI-BRIEFING-LIVE-20260508',
    verifiedAt: '2026-05-08T10:47:00Z',
    reportRefs: ['/app/test_reports/iteration_770.json'],
    liveDataApis: ['/ai-briefing/today', '/ai-briefing/history', '/ai-briefing/preferences'],
    promotedPhase: 'B',
    matchMode: 'exact',
  },
  {
    routePrefix: '/ai-briefing/',
    routeName: 'AI Briefing Trailing Slash Alias',
    evidenceTag: 'W12-E2E-AI-BRIEFING-SLASH-20260508',
    verifiedAt: '2026-05-08T10:47:00Z',
    reportRefs: ['/app/test_reports/iteration_770.json'],
    liveDataApis: ['/ai-briefing/today', '/ai-briefing/history', '/ai-briefing/preferences'],
    promotedPhase: 'B',
    matchMode: 'exact',
  },
  {
    routePrefix: '/ai-briefing/index',
    routeName: 'AI Briefing Index Alias',
    evidenceTag: 'W12-E2E-AI-BRIEFING-INDEX-20260508',
    verifiedAt: '2026-05-08T10:47:00Z',
    reportRefs: ['/app/test_reports/iteration_770.json'],
    liveDataApis: ['/ai-briefing/today', '/ai-briefing/history', '/ai-briefing/preferences'],
    promotedPhase: 'B',
    matchMode: 'exact',
  },
  {
    routePrefix: '/subscription/plans',
    routeName: 'Subscription Plans Route',
    evidenceTag: 'W12-E2E-SUBSCRIPTION-PLANS-LIVE-20260508',
    verifiedAt: '2026-05-08T11:22:00Z',
    reportRefs: ['/app/test_reports/iteration_772.json'],
    liveDataApis: ['/subscriptions/plans', '/subscriptions/status', '/subscriptions/checkout-preview'],
    promotedPhase: 'B',
    matchMode: 'exact',
  },
  {
    routePrefix: '/subscription/plans/',
    routeName: 'Subscription Plans Trailing Slash Alias',
    evidenceTag: 'W12-E2E-SUBSCRIPTION-PLANS-SLASH-20260508',
    verifiedAt: '2026-05-08T11:22:00Z',
    reportRefs: ['/app/test_reports/iteration_772.json'],
    liveDataApis: ['/subscriptions/plans', '/subscriptions/status', '/subscriptions/checkout-preview'],
    promotedPhase: 'B',
    matchMode: 'exact',
  },
  {
    routePrefix: '/subscription/plans/index',
    routeName: 'Subscription Plans Index Alias',
    evidenceTag: 'W12-E2E-SUBSCRIPTION-PLANS-INDEX-20260508',
    verifiedAt: '2026-05-08T11:22:00Z',
    reportRefs: ['/app/test_reports/iteration_772.json'],
    liveDataApis: ['/subscriptions/plans', '/subscriptions/status', '/subscriptions/checkout-preview'],
    promotedPhase: 'B',
    matchMode: 'exact',
  },
  {
    routePrefix: '/subscription/mobile',
    routeName: 'Subscription Mobile Route',
    evidenceTag: 'W12-E2E-SUBSCRIPTION-MOBILE-LIVE-20260508',
    verifiedAt: '2026-05-08T11:22:00Z',
    reportRefs: ['/app/test_reports/iteration_772.json'],
    liveDataApis: ['/subscriptions/status', '/subscriptions/mobile-money/gateways', '/subscriptions/mobile-money/sandbox-info'],
    promotedPhase: 'B',
    matchMode: 'exact',
  },
  {
    routePrefix: '/subscription/mobile/',
    routeName: 'Subscription Mobile Trailing Slash Alias',
    evidenceTag: 'W12-E2E-SUBSCRIPTION-MOBILE-SLASH-20260508',
    verifiedAt: '2026-05-08T11:22:00Z',
    reportRefs: ['/app/test_reports/iteration_772.json'],
    liveDataApis: ['/subscriptions/status', '/subscriptions/mobile-money/gateways', '/subscriptions/mobile-money/sandbox-info'],
    promotedPhase: 'B',
    matchMode: 'exact',
  },
  {
    routePrefix: '/subscription/mobile/index',
    routeName: 'Subscription Mobile Index Alias',
    evidenceTag: 'W12-E2E-SUBSCRIPTION-MOBILE-INDEX-20260508',
    verifiedAt: '2026-05-08T11:22:00Z',
    reportRefs: ['/app/test_reports/iteration_772.json'],
    liveDataApis: ['/subscriptions/status', '/subscriptions/mobile-money/gateways', '/subscriptions/mobile-money/sandbox-info'],
    promotedPhase: 'B',
    matchMode: 'exact',
  },
];

const normalizePath = (routePath: string): string => {
  const route = String(routePath || '').trim();
  if (!route) return '/';
  return route.startsWith('/') ? route : `/${route}`;
};

const getExactAliasCandidates = (normalizedPath: string): string[] => {
  const path = String(normalizedPath || '/').toLowerCase();
  if (path === '/') return ['/'];

  let base = path;
  if (base.endsWith('/index')) {
    base = base.slice(0, -6) || '/';
  } else if (base.endsWith('/') && base !== '/') {
    base = base.slice(0, -1) || '/';
  }

  const variants = [path, base];
  if (base !== '/') {
    variants.push(`${base}/`);
    variants.push(`${base}/index`);
  }

  return Array.from(new Set(variants));
};

export const getRouteE2EEvidenceTag = (routePath: string): RouteE2EEvidenceTag | null => {
  const normalized = normalizePath(routePath).toLowerCase();
  const exactAliases = getExactAliasCandidates(normalized);

  const exactMatch = WAVE3_ROUTE_E2E_EVIDENCE_TAGS.find((item) => {
    if (item.matchMode !== 'exact') return false;
    const prefix = item.routePrefix.toLowerCase();
    return exactAliases.includes(prefix);
  });
  if (exactMatch) return exactMatch;

  const prefixMatch = WAVE3_ROUTE_E2E_EVIDENCE_TAGS.find((item) => {
    if (item.matchMode === 'exact') return false;
    const prefix = item.routePrefix.toLowerCase();
    return normalized === prefix || normalized.startsWith(prefix);
  });
  return prefixMatch || null;
};
