export type CommercialCloneConfig = {
  featureName: string;
  subtitle: string;
  modules: string[];
  apps: string[];
};

export const COMMERCIAL_CLONE_MAP: Record<string, CommercialCloneConfig> = {
  medimate: {
    featureName: "MediMate",
    subtitle: "Inspired clone library of top AI health assistants.",
    modules: ["Symptom Check", "Care Plan", "Medication", "Health Insights"],
    apps: [
      "Ada Health",
      "K Health",
      "Medisafe",
      "Wysa",
      "Fitbit Premium AI",
      "MyFitnessPal AI",
      "Babylon Health",
      "HealthTap",
      "Symptomate",
      "Luffu",
      "Infermedica",
      "Buoy Health",
      "Ada DX",
      "WebMD Symptom Checker",
      "First Opinion Health",
    ],
  },
  pennypilot: {
    featureName: "PennyPilot",
    subtitle: "Full-stack finance clones inspired by leading budgeting apps.",
    modules: ["Budgeting", "Cash Flow", "Subscriptions", "Net Worth"],
    apps: [
      "Mint",
      "Cleo AI",
      "YNAB",
      "Rocket Money",
      "Monarch Money",
      "Copilot Money",
      "Plum AI",
      "Albert AI",
      "PocketGuard",
      "NerdWallet",
      "Cleo+",
      "Emma Finance",
      "Zeta Finance",
      "Spendee",
      "MoneyLion",
      "Chime Budget Tools",
    ],
  },
  assistant: {
    featureName: "TaskTool",
    subtitle: "Productivity clones modeled after top task platforms.",
    modules: ["Task Inbox", "Smart Calendar", "Focus Planning", "Automation"],
    apps: [
      "Notion AI",
      "Todoist",
      "Motion AI",
      "ClickUp AI",
      "Sunsama",
      "Tiimo",
      "Trello AI",
      "Asana AI",
      "Monday.com AI",
      "TickTick",
      "Microsoft To Do AI",
      "Google Tasks AI",
      "Forest App",
      "Habitica AI",
      "Remember The Milk AI",
    ],
  },
  smartbuy: {
    featureName: "SmartBuy",
    subtitle: "Commerce assistants inspired by the best shopping tools.",
    modules: ["Price Compare", "Deals", "Cart Optimization", "Returns"],
    apps: [
      "Klarna AI",
      "Honey AI",
      "Shop AI",
      "Amazon Rufus AI",
      "Google Shopping AI",
      "ShopSavvy",
      "Price.com",
      "BuyScout",
      "Rakuten AI",
      "Keepa",
      "Zillow",
      "Redfin",
      "CarGurus",
      "Carvana",
      "ShopBrain",
      "Slickdeals AI",
      "RebatesMe",
      "Fetch Rewards",
      "DealCatcher AI",
    ],
  },
  fitness: {
    featureName: "Fitness",
    subtitle: "Fitness coaching clones inspired by premium training apps.",
    modules: ["Workout Plans", "Habit Tracking", "Coaching", "Recovery"],
    apps: [
      "Fitbit AI Coach",
      "Freeletics",
      "Nike Training Club",
      "Future Fitness",
      "WHOOP AI Coach",
      "Centr AI",
      "Fitbod",
      "Vi Trainer",
      "Peloton AI",
      "MyFitnessPal AI",
      "Fitia",
      "Strong App",
      "Jefit",
      "8fit",
      "Fitocracy",
      "Trainiac",
    ],
  },
  travelpal: {
    featureName: "TravelPal",
    subtitle: "Travel planning clones inspired by top trip assistants.",
    modules: ["Trip Planning", "Booking Insights", "Packing", "Safety"],
    apps: [
      "Hopper AI",
      "TripIt",
      "Kayak AI",
      "Expedia AI",
      "Skyscanner AI",
      "Google Travel AI",
      "GuideGeek",
      "TripPlanner AI",
      "Roam Around AI",
      "Airbnb AI",
      "Rome2rio",
      "Sygic Travel",
      "PackPoint",
      "Citymapper",
      "TripHobo",
    ],
  },
  grammarly: {
    featureName: "AI Writer",
    subtitle: "Writing assistants inspired by the best AI writing tools.",
    modules: ["Rewrite", "Tone", "Grammar", "Long-form"],
    apps: [
      "ChatGPT",
      "Claude",
      "Gemini",
      "Notion AI",
      "Sudowrite",
      "Writesonic",
      "Rytr",
      "QuillBot",
      "Jasper AI",
      "Copy.ai",
      "genspark.ai",
      "Wordtune",
      "LongShot",
      "Frase",
      "TextCortex AI",
      "ContentBot AI",
    ],
  },
  jasper: {
    featureName: "AI Copywriter",
    subtitle: "Marketing copy clones inspired by conversion platforms.",
    modules: ["Campaign Brief", "Ad Copy", "Landing Page", "SEO"],
    apps: [
      "Jasper AI",
      "Copy.ai",
      "Anyword",
      "Writesonic",
      "Smart Copy (Unbounce)",
      "ClosersCopy",
      "Hypotenuse AI",
      "Peppertype AI",
      "Simplified AI",
      "Copysmith",
      "Conversion.ai",
      "Snazzy AI",
      "AutoWrite App",
      "NeuralText",
    ],
  },
  picsart: {
    featureName: "AI Photo Editor",
    subtitle: "Creative imaging clones inspired by pro editors.",
    modules: ["Enhance", "Background", "Generation", "Brand Kit"],
    apps: [
      "Adobe Firefly",
      "Canva AI",
      "Remini",
      "Luminar AI",
      "Pixelcut",
      "Photoroom",
      "Fotor AI",
      "PicsArt AI",
      "Topaz Photo AI",
      "Snapseed AI",
      "BeFunky AI",
      "Let's Enhance",
      "AI Gahaku",
      "DeepArt.io",
      "Bazaart AI",
      "higgsfield.ai",
      "apob.ai",
    ],
  },
  bemyai: {
    featureName: "AI Vision",
    subtitle: "Computer-vision clones inspired by industry leaders.",
    modules: ["Recognition", "Accessibility", "OCR", "Scene Understanding"],
    apps: [
      "Google Lens",
      "Amazon Rekognition",
      "Clarifai",
      "OpenCV AI",
      "Microsoft Azure Vision",
      "Apple Vision AI",
      "Roboflow",
      "Landing AI",
      "Hive AI",
      "Sightengine",
      "DeepVision AI",
      "Sighthound AI",
      "Imagga",
      "EyeQ",
      "Visenze",
    ],
  },
  zapier: {
    featureName: "AI Automations",
    subtitle: "Workflow automation clones inspired by top platforms.",
    modules: ["Workflow Builder", "Triggers", "Connectors", "Monitoring"],
    apps: [
      "Zapier AI",
      "Make.com",
      "UiPath",
      "Automation Anywhere",
      "Microsoft Power Automate",
      "IFTTT AI",
      "n8n AI",
      "Workato",
      "Pabbly Connect",
      "Tray.io",
      "Trigger.dev",
      "Actiondesk",
      "Automate.io",
      "Elastic.io",
      "PieSync AI",
    ],
  },
  chatgpt: {
    featureName: "AI Chatbot",
    subtitle: "Conversational clones inspired by leading AI assistants.",
    modules: ["General Chat", "Roleplay", "Knowledge", "Support"],
    apps: [
      "ChatGPT",
      "Claude",
      "Gemini",
      "Perplexity AI",
      "Meta AI",
      "Poe AI",
      "Character.AI",
      "Pi AI",
      "Grok",
      "Nexus AI",
      "Intercom AI",
      "LiveChat AI",
      "Drift AI",
      "Tidio AI",
      "ManyChat AI",
      "Corti AI",
      "ThoughtSpot AI",
      "Sentient.io",
      "Narrative Science Quill",
      "Loop AI Labs",
    ],
  },
  cognitive: {
    featureName: "AI Cognitive",
    subtitle: "Reasoning clones inspired by decision intelligence tools.",
    modules: ["Summarization", "Sentiment", "Entity Extraction", "Decision Support"],
    apps: [
      "IBM Watson AI",
      "OpenAI GPT",
      "DeepSeek",
      "Anthropic Claude",
      "Grok AI",
      "Microsoft Copilot",
      "Google Gemini",
      "Lumio AI",
      "Adept AI",
      "Inflection Pi",
      "Aible",
      "ThoughtSpot",
      "Gong AI",
      "Cortex by Outlier",
      "Lucidworks Fusion AI",
    ],
  },
  enterprise: {
    featureName: "AI Enterprise",
    subtitle: "Business platform clones inspired by enterprise AI suites.",
    modules: ["Analytics", "Forecasts", "Ops Planning", "Executive Brief"],
    apps: [
      "Salesforce Einstein",
      "Microsoft Copilot 365",
      "SAP Joule AI",
      "Oracle AI",
      "ServiceNow AI",
      "IBM Watsonx",
      "Palantir AIP",
      "Databricks AI",
      "Snowflake Cortex",
      "HubSpot AI",
      "Sense Search",
      "Meta Search",
      "Presearch",
      "Qwant AI",
      "Oscobo",
    ],
  },
  privatesearch: {
    featureName: "AI Private Search",
    subtitle: "Privacy-first search clones inspired by secure engines.",
    modules: ["Anonymous Search", "Sources", "Fact Check", "Privacy Audit"],
    apps: [
      "Perplexity AI",
      "Kagi AI",
      "You.com AI",
      "Brave Search AI",
      "DuckDuckGo AI",
      "Phind AI",
      "Neeva AI (archived model)",
      "Andi Search",
      "Komo AI",
      "Metaphor AI",
      "Voicemod AI",
      "Altered AI",
      "Speechify AI",
      "Voicely AI",
      "Voxygen AI",
    ],
  },
  speech: {
    featureName: "AI Speech & Vision",
    subtitle: "Speech and voice clones inspired by audio leaders.",
    modules: ["Transcription", "Voice Synthesis", "Translation", "Speaker Insights"],
    apps: [
      "ElevenLabs",
      "Whisper AI",
      "Speechmatics",
      "AssemblyAI",
      "Deepgram",
      "Google Speech-to-Text",
      "Microsoft Azure Speech",
      "PlayHT",
      "Resemble AI",
      "Braina",
      "Spotify Podcasts",
      "Apple Podcasts",
      "Voicemod AI",
      "Altered AI",
      "Speechify AI",
      "Voicely AI",
      "Voxygen AI",
    ],
  },
  "ai-search": {
    featureName: "AI Search",
    subtitle: "Search clones inspired by multi-agent research tools.",
    modules: ["Research", "Cross-Source", "Briefing", "Citations"],
    apps: [
      "Perplexity AI",
      "Google Gemini Search",
      "ChatGPT Search",
      "Bing Copilot Search",
      "You.com AI Search",
      "Andi AI Search",
      "Komo AI",
      "Phind AI",
      "Arc Search AI",
      "Metaphor AI",
      "Brainly AI Search",
      "Knoema AI",
      "Socratic by Google",
      "DuckDuckGo Enhanced AI",
      "ElicitAI",
    ],
  },
  "ai-video": {
    featureName: "AI Video Platform",
    subtitle: "Video creation clones inspired by generative studios.",
    modules: ["Video Generation", "Avatar Studio", "Script-to-Video", "Editing"],
    apps: [
      "Runway ML",
      "Synthesia",
      "Pictory",
      "HeyGen",
      "Luma AI",
      "Sora (OpenAI)",
      "Veed AI",
      "Descript",
      "InVideo AI",
      "Kapwing AI",
      "Magisto AI",
      "Vimeo Create AI",
      "Ve.ai (Video Enhancer)",
      "Shakr AI",
      "Moovly AI",
    ],
  },
};