#!/usr/bin/env bash
# Optional: install a pre-push git hook that runs the SW invariant guard
# locally before any code leaves the developer's machine.
#
# Usage:
#   bash scripts/install-git-hooks.sh
#
# Uninstall:
#   rm .git/hooks/pre-push
set -euo pipefail

cd "$(dirname "$0")/.."
HOOK_DIR=".git/hooks"
HOOK_PATH="$HOOK_DIR/pre-push"

if [[ ! -d "$HOOK_DIR" ]]; then
  echo "❌ $HOOK_DIR missing — are you at the repo root?"
  exit 1
fi

cat > "$HOOK_PATH" <<'HOOK'
#!/usr/bin/env bash
# Auto-generated by scripts/install-git-hooks.sh — edit that script, not this file.
echo "[pre-push] running SW invariant guard..."
if ! bash scripts/ci-sw-guard.sh; then
  echo ""
  echo "❌ Push blocked. Fix the SW invariant failure above and try again."
  echo "   If you intentionally want to bypass: git push --no-verify (DO NOT do this to prod)."
  exit 1
fi
HOOK
chmod +x "$HOOK_PATH"
echo "✔ Installed pre-push hook at $HOOK_PATH"
