import { Platform, StyleSheet } from 'react-native';

export type LoginThemeTokens = {
  bg: string; bgAlt: string; bgCard: string; text: string; text2: string; text3: string;
  gray300: string; gray400: string; cyan: string; neonBlue: string; teal: string; purple: string;
  success: string; error: string; warning: string; warningText: string; purpleText: string;
  errorText: string; successText: string; infoText: string;
  glassBorder: string; glassSurface: string; glassHL: string; white: string; onPrimary: string; overlay: string; isDark: boolean;
};

export function makeStyles(T: LoginThemeTokens) { return StyleSheet.create({
  root: { flex: 1, backgroundColor: T.bg, position: 'relative', overflow: 'hidden' },
  wrapper: { flex: 1 },
  wrapperDesktop: { flexDirection: 'row' },
  formScroll: { flexGrow: 1, paddingHorizontal: 24, paddingVertical: 40 },
  formScrollMobile: { paddingHorizontal: 16, paddingVertical: 28 },
  formScrollCompact: { paddingHorizontal: 12, paddingVertical: 20 },
  glassCard: {
    width: '100%', maxWidth: 460, alignSelf: 'center', backgroundColor: T.glassSurface,
    borderRadius: 24, borderWidth: 1, borderColor: T.glassBorder, padding: 36,
    ...(Platform.OS === 'web' ? { boxShadow: `0 18px 72px rgba(0,0,0,${T.isDark ? '0.5' : '0.12'}), 0 0 52px rgba(0,240,255,${T.isDark ? '0.05' : '0'})`, backdropFilter: 'blur(24px)', WebkitBackdropFilter: 'blur(24px)' } as any : {}),
  },
  glassCardTablet: { maxWidth: 560, padding: 30, borderRadius: 22 },
  glassCardMobile: { maxWidth: 520, padding: 24, borderRadius: 20 },
  glassCardCompact: { padding: 18, borderRadius: 18 },
  logoRow: { flexDirection: 'row', alignItems: 'center', gap: 10, marginBottom: 32 },
  logoText: { color: T.white, fontSize: 19, fontWeight: '800', letterSpacing: -0.3 },
  heading: { color: T.text, fontSize: 28, fontWeight: '800', letterSpacing: -0.5 },
  headingMobile: { fontSize: 24 },
  subheading: { color: T.text2, fontSize: 14, marginTop: 6, marginBottom: 28, lineHeight: 21 },
  subheadingMobile: { fontSize: 13, marginBottom: 22, lineHeight: 19 },
  errBox: { flexDirection: 'row', alignItems: 'flex-start', gap: 8, backgroundColor: (globalThis as any).__alphaColor(T.error, '14'), padding: 14, borderRadius: 14, marginBottom: 18, borderWidth: 1, borderColor: (globalThis as any).__alphaColor(T.error, '44') },
  errText: { color: T.errorText, fontSize: 13, lineHeight: 20, flex: 1 },
  resetSuccessBox: { flexDirection: 'row', alignItems: 'flex-start', gap: 10, backgroundColor: (globalThis as any).__alphaColor(T.success, '14'), padding: 14, borderRadius: 14, marginBottom: 18, borderWidth: 1, borderColor: (globalThis as any).__alphaColor(T.success, '44') },
  resetSuccessTitle: { color: T.successText, fontSize: 13, fontWeight: '800' },
  resetSuccessText: { color: T.isDark ? T.text2 : T.successText, fontSize: 12, lineHeight: 18, marginTop: 4 },
  recoveryBox: { backgroundColor: T.glassSurface, borderWidth: 1, borderColor: T.glassBorder, borderRadius: 16, padding: 16, marginTop: -8, marginBottom: 18, gap: 12 },
  recoveryTitle: { color: T.text, fontSize: 13, fontWeight: '800' },
  recoveryText: { color: T.text2, fontSize: 12, lineHeight: 19, marginTop: 4 },
  recoveryCountdownPill: { alignSelf: 'flex-start', flexDirection: 'row', alignItems: 'center', gap: 6, marginTop: 10, backgroundColor: (globalThis as any).__alphaColor(T.cyan, '14'), borderWidth: 1, borderColor: (globalThis as any).__alphaColor(T.cyan, '33'), paddingHorizontal: 10, paddingVertical: 6, borderRadius: 999 },
  recoveryCountdownText: { color: T.infoText, fontSize: 11, fontWeight: '800' },
  recoveryActionsRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
  recoveryPrimaryBtn: { backgroundColor: T.neonBlue, paddingHorizontal: 14, paddingVertical: 10, borderRadius: 10 },
  recoveryPrimaryBtnText: { color: T.onPrimary, fontSize: 12, fontWeight: '800' },
  recoverySecondaryBtn: { backgroundColor: T.glassHL, paddingHorizontal: 14, paddingVertical: 10, borderRadius: 10, borderWidth: 1, borderColor: T.glassBorder },
  recoverySecondaryBtnText: { color: T.text2, fontSize: 12, fontWeight: '700' },
  guidanceBox: { backgroundColor: T.glassSurface, borderWidth: 1, borderColor: T.glassBorder, borderRadius: 16, padding: 16, marginTop: -4, marginBottom: 18 },
  guidanceTitle: { color: T.text, fontSize: 13, fontWeight: '800', marginBottom: 8 },
  guidanceMessage: { color: T.text2, fontSize: 12, lineHeight: 18, marginBottom: 10 },
  guidanceStepRow: { flexDirection: 'row', alignItems: 'flex-start', gap: 8, marginBottom: 8 },
  guidanceStepIndex: { color: T.cyan, fontSize: 12, fontWeight: '800', minWidth: 18 },
  guidanceStepText: { color: T.text2, fontSize: 12, lineHeight: 18, flex: 1 },
  guidanceEmailHint: { color: T.infoText, fontSize: 11, fontWeight: '700', marginTop: 4 },
  guidanceActionsRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 10, marginTop: 10 },
  guidancePrimaryBtn: { backgroundColor: T.neonBlue, paddingHorizontal: 14, paddingVertical: 10, borderRadius: 10 },
  guidancePrimaryBtnText: { color: T.onPrimary, fontSize: 12, fontWeight: '800' },
  tabs: { flexDirection: 'row', backgroundColor: T.glassSurface, borderRadius: 14, padding: 4, borderWidth: 1, borderColor: T.glassBorder, marginBottom: 22 },
  tab: { flex: 1, flexDirection: 'row', paddingVertical: 10, borderRadius: 10, alignItems: 'center', justifyContent: 'center' },
  tabActive: { backgroundColor: T.neonBlue },
  tabText: { fontSize: 12, fontWeight: '700', color: T.text3 },
  tabTextActive: { color: T.onPrimary },
  field: { marginBottom: 16 },
  credentialsCluster: { marginBottom: 4 },
  credentialsClusterTablet: { marginBottom: 6 },
  credentialsClusterDesktop: { marginBottom: 8 },
  credentialField: { marginBottom: 14 },
  label: { color: T.text2, fontSize: 11, fontWeight: '700', marginBottom: 8, letterSpacing: 1.2, textTransform: 'uppercase' },
  inputRow: { flexDirection: 'row', alignItems: 'center', backgroundColor: T.glassSurface, borderRadius: 12, paddingHorizontal: 14, height: 50, borderWidth: 1, borderColor: T.glassBorder },
  credentialInputRow: { minHeight: 52, borderRadius: 13 },
  credentialInputRowTablet: { minHeight: 54 },
  credentialInputRowDesktop: { minHeight: 56 },
  inputRowFocused: { borderColor: (globalThis as any).__alphaColor(T.cyan, '60'), ...(Platform.OS === 'web' ? { boxShadow: '0 0 12px rgba(0,240,255,0.12)' } as any : {}) },
  input: { flex: 1, fontSize: 14, color: T.text },
  credentialInput: { fontSize: 15, lineHeight: 20 },
  forgotLink: { color: T.cyan, fontSize: 11, fontWeight: '600', letterSpacing: 0.5 },
  hintText: { color: T.text2, fontSize: 12, marginBottom: 8 },
  strengthRow: { flexDirection: 'row', alignItems: 'center', gap: 10, marginBottom: 14, marginTop: -6 },
  strengthTrack: { flexDirection: 'row', gap: 4, flex: 1 },
  strengthSeg: { flex: 1, height: 3, borderRadius: 2 },
  strengthLabel: { fontSize: 11, fontWeight: '700', letterSpacing: 0.5 },
  primaryBtn: { height: 50, borderRadius: 12, justifyContent: 'center', alignItems: 'center', marginTop: 4, backgroundColor: T.neonBlue, ...(Platform.OS === 'web' ? { cursor: 'pointer' } as any : {}) },
  primaryBtnText: { color: T.onPrimary, fontSize: 14, fontWeight: '700', letterSpacing: 1.2 },
  secondaryBtn: { flexDirection: 'row', backgroundColor: T.glassSurface, height: 46, borderRadius: 12, justifyContent: 'center', alignItems: 'center', borderWidth: 1, borderColor: T.glassBorder, marginBottom: 12 },
  secondaryBtnText: { color: T.text, fontSize: 14, fontWeight: '700' },
  divider: { flexDirection: 'row', alignItems: 'center', marginVertical: 20 },
  dividerLine: { flex: 1, height: 1, backgroundColor: T.glassBorder },
  dividerText: { color: T.text3, paddingHorizontal: 14, fontSize: 11, fontWeight: '600', letterSpacing: 1.5 },
  socialRow: { flexDirection: 'row', gap: 10, overflow: 'visible' as const },
  compactSocialRow: { flexDirection: 'row', gap: 10 },
  compactSocialButton: { minHeight: 44 },
  socialBtn: { flex: 1, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8, height: 48, borderRadius: 12, borderWidth: 1.5, borderColor: T.glassBorder, backgroundColor: T.bgAlt, position: 'relative' as const, overflow: 'hidden' as const, color: T.text },
  socialBtnText: { color: T.text, fontSize: 13, fontWeight: '600' },
  lastUsedSocialBtn: { borderColor: (globalThis as any).__alphaColor(T.cyan, '50'), backgroundColor: (globalThis as any).__alphaColor(T.cyan, '0A') },
  lastUsedTag: { position: 'absolute' as const, top: 2, right: 2, backgroundColor: T.cyan, fontSize: 7, fontWeight: '800', paddingHorizontal: 4, paddingVertical: 1, borderRadius: 3, overflow: 'hidden' as const, letterSpacing: 0.3, zIndex: 10 },
  lastUsedDot: { width: 5, height: 5, borderRadius: 3, backgroundColor: T.cyan, marginLeft: 4 },
  quickRow: { flexDirection: 'row', gap: 10, marginTop: 12 },
  compactQuickRow: { flexDirection: 'row', gap: 10 },
  compactQuickButton: {},
  quickBtn: { flex: 1, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 6, height: 42, borderRadius: 10, borderWidth: 1, borderColor: T.glassBorder, backgroundColor: 'transparent' },
  quickBtnActive: { borderColor: (globalThis as any).__alphaColor(T.cyan, '40'), backgroundColor: (globalThis as any).__alphaColor(T.cyan, '08') },
  quickBtnText: { color: T.text3, fontSize: 12, fontWeight: '600' },
  secBadge: { flexDirection: 'row', justifyContent: 'center', alignItems: 'center', gap: 6, marginTop: 20, paddingVertical: 8 },
  secText: { color: T.text3, fontSize: 10, fontWeight: '600', letterSpacing: 0.5 },
  secDot: { width: 3, height: 3, borderRadius: 2, backgroundColor: (globalThis as any).__alphaColor(T.text3, '40') },
  registerRow: { flexDirection: 'row', justifyContent: 'center', marginTop: 16 },
  registerText: { color: T.text3, fontSize: 13 },
  registerLink: { color: T.cyan, fontSize: 13, fontWeight: '700' },
  guestBtn: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', marginTop: 10, paddingVertical: 6 },
  guestBtnText: { color: T.text3, fontSize: 12, fontWeight: '500' },
  mobileKpi: { flexDirection: 'row', justifyContent: 'center', gap: 12, paddingHorizontal: 24, paddingBottom: 24, paddingTop: 8 },
  mobileKpiCard: { flex: 1, alignItems: 'center', paddingVertical: 12, borderRadius: 12, backgroundColor: T.glassSurface, borderWidth: 1, borderColor: T.glassBorder, ...(Platform.OS === 'web' ? { backdropFilter: 'blur(12px)', WebkitBackdropFilter: 'blur(12px)' } as any : {}) },
  mobileKpiVal: { fontSize: 18, fontWeight: '800' },
  mobileKpiLabel: { color: T.text3, fontSize: 10, fontWeight: '600', marginTop: 2, letterSpacing: 0.5 },
  modalOverlay: { flex: 1, backgroundColor: T.overlay, justifyContent: 'center', alignItems: 'center', padding: 24 },
  modalCard: { backgroundColor: T.bgCard, borderRadius: 24, padding: 32, width: '100%', maxWidth: 420, borderWidth: 1, borderColor: T.glassBorder, ...(Platform.OS === 'web' ? { boxShadow: '0 0 80px rgba(0,240,255,0.06), 0 24px 80px rgba(0,0,0,0.5)' } as any : {}) },
  modalIconWrap: { width: 64, height: 64, borderRadius: 32, backgroundColor: (globalThis as any).__alphaColor(T.cyan, '12'), alignItems: 'center', justifyContent: 'center', marginBottom: 16, borderWidth: 1, borderColor: (globalThis as any).__alphaColor(T.cyan, '20') },
  modalTitle: { fontSize: 20, fontWeight: '800', color: T.white, marginBottom: 6, letterSpacing: -0.3 },
  modalSub: { fontSize: 13, color: T.text2, textAlign: 'center' },
  otpDisplay: { backgroundColor: (globalThis as any).__alphaColor(T.cyan, '08'), borderRadius: 14, padding: 18, marginBottom: 16, width: '100%', borderWidth: 1, borderColor: (globalThis as any).__alphaColor(T.cyan, '12') },
}); }